nodeLinker: pnp

packageExtensions:
  "@types/babel__core@*":
    peerDependencies:
      "@babel/generator": "*"
      "@babel/template": "*"
      "@babel/traverse": "*"
  debug@*:
    peerDependencies:
      supports-color: "*"
  eslint-module-utils@*:
    peerDependencies:
      eslint-import-resolver-node: "*"
  webpack@*:
    peerDependencies:
      "@types/json-schema": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-berry.cjs
